### DISCUSSION TITLE
Running on a public link

### DISCUSSION THREAD

**Discussion by spuliz** [AbdBarho/stable-diffusion-webui-docker#232] [General]
Hi, I installed the docker on a ec-2 instance but I am not able to run the web ui on a public  URL. 
When starting the docker I can read the message " To create a public link, set `share=True` in `launch()`." but what does that mean? Which file contains the launch function?
Thanks.

**Comment by AbdBarho** [comment]
there are 2 aspects here:

1. you can get the public IP of your ec2 instance (if you have configured any), then the UI should be accessable at `IP:7860`
2. if you want to use the share feature from gradio (the one you see in the console), create a file called `docker-compose.override.yml` and add this to it:
```yml
services:
  auto:
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --share
```
`--share` is the the important flag here.
