### DISCUSSION TITLE
mount the .cache directory (which stores huggingface downloads) as a docker volume pointing to ~/.cache

### DISCUSSION THREAD

**Discussion by AskAlice** [AbdBarho/stable-diffusion-webui-docker#268] [General]
currently if invoke ai downloads/installs any configs using the huggingface library (which downloads blobs of the repos instead of files), the `.cache` goes into the .data folder, but users might have other applications that would like to re-use the models stored there.

I think the .cache dir should be mounted by default... like this for example
```
x-base_service: &base_service
  ports:
    - "7860:7860"
  volumes:
    - &v1 ./data:/data
    - &v2 ./output:/output
    - &v3 ./../.cache/:/data/.cache
    ```
