### DISCUSSION TITLE
--cors-allow-origins-regex not working, but it works in the normal A1111 repo

### DISCUSSION THREAD

**Discussion by Keavon** [AbdBarho/stable-diffusion-webui-docker#329] [General]
I have a `docker-compose.override.yml` with this
```
services:
  auto:
    environment:
      # - CLI_ARGS=--xformers --nowebui --cors-allow-origins=*
      - CLI_ARGS=--xformers --nowebui --cors-allow-origins-regex="https?://((localhost|127\.0\.0\.1|192\.168\.\d+\.\d+):\d+|(editor|dev)\.graphite\.rs|.*\.graphite\-master\.pages\.dev)"
```

Using this Docker container, `--cors-allow-origins-regex` does not seem to work. Browser requests receive an invalid CORS error. But switching to the `--cors-allow-origins=*` version does work.

I tested the same regex command on the ordinary A1111 repository (using Windows cmd.exe) and it works. Requests don't fail the CORS check.

I'm out of ideas, so I'm posting here for advice. Thanks.
