### DISCUSSION TITLE
[automatic1111] textual_inversion_templates folder

### DISCUSSION THREAD

**Discussion by MylesLandais** [AbdBarho/stable-diffusion-webui-docker#344] [Q&A] [answered]
Can't seem to find the `textual_inversion_templates` folder when using the stable diffusion UI

I've tried creating the folder in `/data` but it doesn't seem to map correctly

Does anyone have this working?

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion#training-an-embedding

**Comment by AbdBarho** [comment]
I think this is the folder you are looking for?

https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/master/textual_inversion_templates

I have not used the feature, if you face any problems related to this repo, feel free to comment.

**Comment by MylesLandais** [comment, marked as answer]
creating custom templates does not appear in the list when refreshing.

I've tried creating the folder in a number of locations and i thought `\data\config\auto\textual_inversion_templates` would work but they dont appear in the UI after restarting the container.

**Reply by AbdBarho** [reply]
Is this what you are looking for?

![image](https://user-images.githubusercontent.com/24505302/222244202-b0067ccf-cd35-4790-8167-f8b8d1909590.png)

**Reply by MylesLandais** [reply]
they should show up under this list, and it looks like there is a command line flag that can set the directory to watch.


![image](https://user-images.githubusercontent.com/6424365/222282133-04345f2c-ea55-4166-b77e-aacbd626b333.png)

**Reply by AbdBarho** [reply]
Aha, I see, you probably need this parameter: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8/modules/shared.py#L40

You can create a `docker-compose.override.yaml` and put this into it:

```yaml
services:
   auto:
     environment:
       # update the cli args to match your needs
       - CLI_ARGS=--textual-inversion-templates-dir /data/templates --allow-code --medvram --xformers --enable-insecure-extension-access --api
```
