### DISCUSSION TITLE
Add offline option to better support stateless and offline environments

### DISCUSSION THREAD

**Discussion by qingfengfenga** [AbdBarho/stable-diffusion-webui-docker#398] [Show and tell]
Add offline option to better support stateless and offline environments

https://github.com/qingfengfenga/stable-diffusion-webui-docker

```
docker compose --profile download up --build
# wait until its done, then:

docker compose --profile [ui] up --build
# where [ui] is one of: invoke | auto | auto-cpu | sygil | sygil-sl

docker compose --profile [ui]-offline up --build
# where [ui] is one of: invoke | auto | auto-cpu | sygil | sygil-sl
# Afterwards, all you need is a docker-compose.yml and offline image to start the service in the new environment

docker compose --profile [ui]-offline up -d
# where [ui] is one of: invoke | auto | auto-cpu | sygil | sygil-sl
```

**Comment by AbdBarho** [comment]
unfortunately, I don't have control over what the UIs do, this repo just packages them in a container.

This should be a feature request in the corresponding UI, not here.

**Reply by qingfengfenga** [reply]
> unfortunately, I don't have control over what the UIs do, this repo just packages them in a container.
> 
> This should be a feature request in the corresponding UI, not here.

Perhaps the use of the ui offline name here is ambiguous and can be further modified.

During the process of packaging the UI into a container, this repository separately processes the data directory, allowing multiple UIs to share the data directory.

The generated images do not contain data. If I want to use the generated images elsewhere (in a stateless or offline environment) and cannot mount the data directory, I need to download the data from the data directory again every time I start.

The specific operation of the ui-offline option is to copy the downloaded data directory from the download container to the corresponding image, and generate an image containing data, that's all.



### commit 
https://github.com/qingfengfenga/stable-diffusion-webui-docker/commit/a09d510c642d94286a5b2298a5ec217b4bec160f

### yaml part
```
  auto-offline: &automatic-offline
    <<: *base_service_offline
    profiles: ["auto-offline"]
    build:
      context: .
      dockerfile: ./services/AUTOMATIC1111/Dockerfile-offline
    image: sd-auto-offline:49
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
```

### Dockerfile-offline examples
```
FROM sd-auto:49

RUN rm -rf /data && mkdir -p /data

COPY ./data /data
```
