### DISCUSSION TITLE
Changing a port is difficult without editing `docker-compose.yml` (Updating via git pull is difficult)

### DISCUSSION THREAD

**Discussion by LEv145** [AbdBarho/stable-diffusion-webui-docker#430] [Show and tell]
Due to the fact that docker-compose specifies `ports` for all profiles:
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/445f3f8bac144adc2645eb68a8e6f0c22020627a/docker-compose.yml#L4-L5
it is difficult to launch multiple profiles with different ports

And if you specify `ports` in `docker-compose.override.yml`, then they are not overridden, but merged:
`docker-compose.override.yml`:
```yml
services:
  invoke:
    ports:
      - "7861:7860"
```
Result:
```yml
services:
  invoke:
    ...
    ports:
      - "7860:7860"
      - "7861:7860"
```

https://docs.docker.com/compose/extends/#adding-and-overriding-configuration

**Comment by LEv145** [comment]
Сan specify different ports for each profile in `docker-compose.yml`:
```yml
services:
  auto: &automatic
    ...
    profiles: ["auto"]
    ports: ["7860:7860"]

  invoke:
    ...
    profiles: ["invoke"]
    ports: ["7861:7860"]
```
