### DISCUSSION TITLE
Is there any harm to changing the volume mounts?

### DISCUSSION THREAD

**Discussion by RiffyDivine** [AbdBarho/stable-diffusion-webui-docker#633] [Q&A]
Just wanted to make sure I won't break anything as I am not used to seeing &vx for a mount. But I wanted to redirect the output one to my nas via a nfs share, will that break anything/is it depending on it being ./output? Also can the data and build ones be changed also as needed?

**Comment by devingfx** [comment]
Hi!

The syntax `&v1` and `*v1` are YAML aliases  (the file format) and not specific to docker or the webUIs... The former `&alias value` syntax define an alias name for the value next to it, and `*alias` recall the value at this place. The goal is only to not duplicate data, and also to avoid having to update the same value at several places in the document...
So just forget it because anyway there is just `*v1` used in the download service section.

Concerning the docker volumes: 
I successfully added some other volumes in section `x-base-service` (that is inherited by each webUIs), but there is some caveats!
- Do not modify existing volumes as it may break stuff ! Just add some, pointing to sub-folders:
  ```yaml
  x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
      - &v3 /home/dig/dev/AI/models/img:/data/models
      - &v4 /home/dig/Images/AI/ComfyUI:/output/comfy
  ```
- Here the `/data/models` folder (into the container) is my host's model folder (with several models from earlier Auto1111 install), but the sub-folders names are not the same for each UI so you have to manually craft symlinks for each UI to have sub-folders named as it expects... (not ideal) (ex: lora > Lora)
- The host's output folder is correctly populated with container generated images, but the files inherits docker's runtime permission, in my case it runs with root user (linux), so my usual user is not able to read/modify/move/delete any image, I have to change premissions before any operations (with sudo, because I'm a power user of this computer).
- I'm using only ComfyUI right now so I can't garanty this setup works for other webUIs ...
