### DISCUSSION TITLE
Can I run both automatic1111 and comfy? Here is my docker compose file

### DISCUSSION THREAD

**Discussion by fahadshery** [AbdBarho/stable-diffusion-webui-docker#724] [Q&A]
Hi,

I am running stable diffusion with automatic1111 with no issues.
I want to run `comfy` as well.
Here is my current `docker-compose.yml`. 
Any pointers?
```
#  AI Stack consists of the following:
# - Ollama
# - Open Web UI
# - Stable Diffusion
# - Whisper
# - Traefik

#-Available models: • https://ollama.com/library/

services:

# Ollama
# uncomment if deploying ollama using docker. But I have been having some issues using it so I installed
# bare metal. and therefore no need to install it but if you want to deploy using docker then uncomment

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID:-1000}
  #     - PGID=${PGID:-1000}
  #     - OLLAMA_KEEP_ALIVE=24h
  #     - ENABLE_IMAGE_GENERATION=True
  #     - COMFYUI_BASE_URL=http://stable-diffusion-webui:7860
  #   networks:
  #     - traefik
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #     - ./ollama:/root/.ollama
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.ollama.rule=Host(`ollama.local.example.com`)"
  #     - "traefik.http.routers.ollama.entrypoints=https"
  #     - "traefik.http.routers.ollama.tls=true"
  #     - "traefik.http.routers.ollama.tls.certresolver=cloudflare"
  #     - "traefik.http.routers.ollama.middlewares=default-headers@file"
  #     - "traefik.http.routers.ollama.middlewares=ollama-auth"
  #     - "traefik.http.services.ollama.loadbalancer.server.port=11434"
  #     - "traefik.http.routers.ollama.middlewares=auth"
  #     - "traefik.http.middlewares.auth.basicauth.users=${OLLAMA_API_CREDENTIALS}"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

# open web ui

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      # - 'OLLAMA_BASE_URL=http://ollama:11434'
      # - 'OLLAMA_BASE_URL=http://{{ ollama_server_ip }}:11434'
      - 'OLLAMA_BASE_URL=http://192.168.1.2:11434'
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./open-webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`chat.local.example.com`)"
      - "traefik.http.routers.open-webui.entrypoints=https"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.tls.certresolver=cloudflare"
      - "traefik.http.routers.open-webui.middlewares=default-headers@file"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    # depends_on:
      # - ollama
    extra_hosts:
      - host.docker.internal:host-gateway

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    networks:
      - traefik
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./searxng:/etc/searxng
    depends_on:
      # - ollama
      - open-webui
    restart: unless-stopped

# Fabric

  fabric:
    build: ./fabric
    image: fabric
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./fabric:/home/appuser/.config/fabric
    depends_on:
      # - ollama
      - open-webui
    tty: true
    restart: unless-stopped
    networks:
      - traefik

  # stable diffusion

  stable-diffusion-base-download:
    build: ./stable-diffusion-webui-docker/services/download/
    image: stable-diffusion-base
    container_name: stable-diffusion-base
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./stable-diffusion-webui-docker/data:/data

  automatic1111-stable-diffusion-webui:
    build: ./stable-diffusion-webui-docker/services/AUTOMATIC1111/
    image: automatic1111
    container_name: automatic1111
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./stable-diffusion-webui-docker/data:/data
      - ./stable-diffusion-webui-docker/output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stable-diffusion.rule=Host(`ai-images.local.example.com`)"
      - "traefik.http.routers.stable-diffusion.entrypoints=https"
      - "traefik.http.routers.stable-diffusion.tls=true"
      - "traefik.http.routers.stable-diffusion.tls.certresolver=cloudflare"
      - "traefik.http.services.stable-diffusion.loadbalancer.server.port=7860"
      - "traefik.http.routers.stable-diffusion.middlewares=default-headers@file"

#   comfy-webui:
#     build: ./stable-diffusion-webui-docker/services/comfy/
#     image: comfy-ui
#     environment:
#       - PUID=${PUID:-1000}
#       - PGID=${PGID:-1000}
#       - CLI_ARGS=
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./stable-diffusion-webui-docker/data:/data
#       - ./stable-diffusion-webui-docker/output:/output
#     stop_signal: SIGKILL
#     tty: true
#     deploy:
#       resources:
#         reservations:
#           devices:
#               - driver: nvidia
#                 device_ids: ['0']
#                 capabilities: [compute, utility]
#     restart: unless-stopped
#     networks:
#       - traefik
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.stable-diffusion.rule=Host(`comfy.local.example.com`)"
#       - "traefik.http.routers.stable-diffusion.entrypoints=https"
#       - "traefik.http.routers.stable-diffusion.tls=true"
#       - "traefik.http.routers.stable-diffusion.tls.certresolver=cloudflare"
#       - "traefik.http.services.stable-diffusion.loadbalancer.server.port=7860"
#       - "traefik.http.routers.stable-diffusion.middlewares=default-headers@file"

networks:
  traefik:
    external: true
```
