### DISCUSSION TITLE
A work-around to update ComfyUI (Flux+SD3) - Nvidia GPU

### DISCUSSION THREAD

**Discussion by feickoo** [AbdBarho/stable-diffusion-webui-docker#740] [Show and tell]
Basically All I did was to modify the dockerfile.
The first file to modify is /service/comfy/Dockerfile
update the first line to `FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime` so we can have the latest dependency version
And we remove the line `git reset --hard 276f8fce9f5a80b500947fb5745a4dde9e84622d && \ `so we can have the latest version of ComfyUI.

The full file will look like
```dockerfile
FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1

RUN apt-get update && apt-get install -y git && apt-get clean

ENV ROOT=/stable-diffusion
RUN --mount=type=cache,target=/root/.cache/pip \
  git clone https://github.com/comfyanonymous/ComfyUI.git ${ROOT} && \
  cd ${ROOT} && \
  git checkout master && \
  pip install -r requirements.txt

WORKDIR ${ROOT}
COPY . /docker/
RUN chmod u+x /docker/entrypoint.sh && cp /docker/extra_model_paths.yaml ${ROOT}

ENV NVIDIA_VISIBLE_DEVICES=all PYTHONPATH="${PYTHONPATH}:${PWD}" CLI_ARGS=""
EXPOSE 7860
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD python -u main.py --listen --port 7860 ${CLI_ARGS}
```

Now within the same folder, we modify extra_model_paths.yaml. This file will make ComfyUI to use the proper folders to load our models for Flux and SD3.

```yaml
a111:
  base_path: /data

  checkpoints: models/Stable-diffusion
  configs: models/Stable-diffusion
  vae: models/VAE
  loras: |
    models/Lora
    models/LyCORIS
  upscale_models: |
    models/RealESRGAN
    models/ESRGAN
    models/SwinIR
    models/GFPGAN
  hypernetworks: models/hypernetworks
  controlnet: models/ControlNet
  gligen: models/GLIGEN
  clip: models/CLIPEncoder
  embeddings: embeddings

  custom_nodes: config/comfy/custom_nodes

  # adding new features to comfyUI
comfyui:
  base_path: /data

  clip: models/clip/
  clip_vision: models/clip_vision/
  diffusion_models: |
    models/diffusion_models
    models/unet
```

after saving, go back to spin up `sudo docker compose --profile comfy up --build` and you should be ready to go. remember to put flux in unet folder and SD3 in diffusion_models
