### DISCUSSION TITLE
Missing Models: text_encoders, diffusion_models

### DISCUSSION THREAD

**Discussion by juanca** [AbdBarho/stable-diffusion-webui-docker#763] [Q&A]
I am trying out a template for text to video. I was able to download the missing models but can't seem to figure out where to place them. 

```
Missing Models

When loading the graph, the following models were not found:

- text_encoders / umt5_xxl_fp8_e4m3fn_scaled.safetensors
- diffusion_models / wan2.1_t2v_1.3B_fp16.safetensors
```

Chatgpt / google doesn't seem to give correct answers on where to place these downloaded files (why can't comfyui webui / comfyui-manager download these to the correct place?).

I tried:

- /data/models/text_encoders (had to create this directory)
- /data/models/diffusion_models (had to create this directory)
- /data/models/unet (had to create this directory)
- /data/models/clip
- /data/models/Stable-diffusion
- equivalent in: /stable-diffusion/models/

Nothing seems to work.

Whenever I place files in these directories and try to run the workflow. I get the following error message:

```
Prompt outputs failed validation: 
UNETLoader:
    - Value not in list: unet_name: 'wan2.1_t2v_1.3B_fp16.safetensors' not in []
CLIPLoader:
    - Value not in list: clip_name: 'umt5_xxl_fp8_e4m3fn_scaled.safetensors' not in []
```

Where am I suppose to place these files? How would I know where to place them? How do I reload comfyui after moving files? Do I always need to restart the docker container?

I am choosing to open this issue here because it seems like it has to do with how `/data/` is mapped into comfyui.

**Comment by juanca** [comment]
I found the answer for clips.

```
root@da23463ab9d1:/data/models# cat /stable-diffusion/extra_model_paths.yaml
a111:
  base_path: /data

  checkpoints: models/Stable-diffusion
  configs: models/Stable-diffusion
  vae: models/VAE
  loras: models/Lora
  upscale_models: |
    models/RealESRGAN
    models/ESRGAN
    models/SwinIR
    models/GFPGAN
  hypernetworks: models/hypernetworks
  controlnet: models/ControlNet
  gligen: models/GLIGEN
  clip: models/CLIPEncoder
  embeddings: embeddings
```

Looks like we renamed the clip folder to CLIPEncoder. 

I am making an attempt at documenting these paths. 

I am still unsure about the unet files. What kind are those?
