### ISSUE TITLE
Wsl docker windows，How to use the specified graphics card for running

### ISSUE THREAD

**Issue by pengkaiwei** [AbdBarho/stable-diffusion-webui-docker#174]
Wsl docker windows，How to use the specified graphics card for running.

I have two Nvidia graphics cards, one A4000 and one P106-100. I want to try the P106-100

Similar question here, but I don't know how to set it up in docker.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3156

Tks !

**Comment by AbdBarho** [comment]
you can create a file in the root of the repo called `docker-compose.override.yml` and put this in it:

```yml
services:
  auto:
   deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['1'] # 0 or 1, depending on the graphics card
                capabilities: [gpu]
```
