### ISSUE TITLE
Moving the `--theme dark` flag from Dockerfile to docker-compose.yml

### ISSUE THREAD

**Issue by Keavon** [AbdBarho/stable-diffusion-webui-docker#204]
Since not everyone wants the dark theme in the AUTOMATIC1111 web UI, wouldn't it make more sense to move the `--theme dark` flag into the environment variables set in `docker-compose.yml`? I currently track your repository but I have one commit that I rebase which just changes those environment variables in `docker-compose.yml` (removing `--allow-code --medvram` and adding `--api` for my purposees). Not having to rebase two files would make it slightly easier to maintain. Thanks for considering.

**Comment by AbdBarho** [comment]
@Keavon I removed it in #205 

that being said, you don't an extra commit that you have to always rebase for this, you can leave the original docker compose file as is, and create a `docker-compose.override.yml` and put this in it:
```yml
services:
  auto:
    environment:
      - CLI_ARGS=--api # your args here
    # you can even override the entire command if you want to
    command: [python3, -u, ../../webui.py, --listen, --port, 1111, --beep, --beep, --iamasheep]
```
