### ISSUE TITLE
Is CPU-Only Usage Possible?

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [AbdBarho/stable-diffusion-webui-docker#40]
Hello,
I really love what you're doing here. Unfortunately I don't have a system with a GPU to throw at this. Is it possible to do it only in CPU? I saw that there is the vino project for that however it doesn't have nearly the same features of this project.

**Comment by AbdBarho** [comment]
That is a really good question, I will do some testing and report back

**Comment by GeorgiaM-honestly** [comment]
Okay. I got it to start though it complains:

```
 ⠿ Container stable-diffusion-webui-docker-model-1  Running                                                                                                                                         0.0s
Attaching to stable-diffusion-webui-docker-model-1
stable-diffusion-webui-docker-model-1  | Global Step: 470000
stable-diffusion-webui-docker-model-1  | UNet: Running in eps-prediction mode
stable-diffusion-webui-docker-model-1  | Traceback (most recent call last):
stable-diffusion-webui-docker-model-1  |   File "scripts/webui.py", line 449, in <module>
stable-diffusion-webui-docker-model-1  |     model,modelCS,modelFS,device, config = load_SD_model()
stable-diffusion-webui-docker-model-1  |   File "scripts/webui.py", line 420, in load_SD_model
stable-diffusion-webui-docker-model-1  |     model.cuda()
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 127, in cuda
stable-diffusion-webui-docker-model-1  |     return super().cuda(device=device)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
stable-diffusion-webui-docker-model-1  |     return self._apply(lambda t: t.cuda(device))
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
stable-diffusion-webui-docker-model-1  |     module._apply(fn)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
stable-diffusion-webui-docker-model-1  |     module._apply(fn)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
stable-diffusion-webui-docker-model-1  |     module._apply(fn)
stable-diffusion-webui-docker-model-1  |   [Previous line repeated 1 more time]
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
stable-diffusion-webui-docker-model-1  |     param_applied = fn(param)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
stable-diffusion-webui-docker-model-1  |     return self._apply(lambda t: t.cuda(device))
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
stable-diffusion-webui-docker-model-1  |     torch._C._cuda_init()
stable-diffusion-webui-docker-model-1  | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
stable-diffusion-webui-docker-model-1 exited with code 1
```

Therefore I looked at the CLI flags and changed the yaml config to:

```
version: '3.9'

services:
  model:
    build:
      context: ./hlky/
      args:
        # You can choose any commit sha from https://github.com/hlky/stable-diffusion/commits/main
        # USE AT YOUR OWN RISK! otherwise just leave it empty.
        WEBUI_SHA:
    restart: on-failure
    ports:
      - "7860:7860"
    volumes:
      - ./cache:/cache
      - ./output:/output
      - ./models:/models
    environment:
# Default
#      - CLI_ARGS=--extra-models-cpu --optimized-turbo
# https://github.com/hlky/stable-diffusion/blob/bb765f1897c968495ffe12a06b421d97b56d5ae1/scripts/webui.py
      - CLI_ARGS=--extra-models-cpu --optimized-turbo --esrgan-cpu --gfpgan-cpu
#    deploy:
#      resources:
#        reservations:
#          devices:
#              - driver: nvidia
#                device_ids: ['0']
#                capabilities: [gpu]

```

Now, despite the error, the container IS running and taking up some resources. However when I try to connect to 127.0.0.1:7860 from the system the docker is running on, I get connection refused:

```
nc 127.0.0.1 7860
(UNKNOWN) [127.0.0.1] 7860 (?) : Connection refused
```

Which is curious, because it is listening:

```
netstat -anp | grep :7860
tcp        0      0 0.0.0.0:7860            0.0.0.0:*               LISTEN      3679/docker-proxy   
tcp6       0      0 :::7860                 :::*                    LISTEN      3685/docker-proxy   
```

Maybe i'm missing something :P

**Comment by AbdBarho** [comment]
@GeorgiaM-honestly you can stop the container with `docker compose down` 

I am still looking into the cpu stuff

**Comment by AbdBarho** [comment]
@GeorgiaM-honestly here is how to run it on cpu


```
cd AUTOMATIC1111
```
update the docker compose file

```
version: '3.9'

services:
  model:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ../cache:/cache
      - ../output:/output
      - ../models:/models
    environment:
      - CLI_ARGS=--no-half --precision full
```
then
```
docker compose up --build
```

I only tested 64x64, but it seems to work.
