### ISSUE TITLE
Cannot find the directory where train data is stored

### ISSUE THREAD

**Issue by tomato-ga** [AbdBarho/stable-diffusion-webui-docker#438]
I always use it with docker. Thank you!

https://github.com/liasece/sd-webui-train-tools
I used this train-tools to create Lora.

Then, it says that it saved the safetensors file in the following directory, but I can't find it by using find or grep commands.

`outputs/train_tools/projects/likeface/versions/v1/trains/chilled_remix_v1vae-bs-1-ep-20-op-Lion-lr-0_0001-net-128-ap-64/likeface-v 1.safetensors`

The `data` and `output` directories are there, but the `outputs` directory was not found.

Is it stored somewhere?

<img width="587" alt="スクリーンショット 2023-05-04 13 08 43" src="https://user-images.githubusercontent.com/52771764/236110794-5ce9c2f8-d929-44d3-9dc0-416fa62ab426.png">

**Comment by AbdBarho** [comment]
the `outputs` folder is not mounted, you can either mount it and restart the container, or you can copy the files out of the container.

If you could change the output path to `/output/train_tools/....` it would make your life easier.

**Comment by tomato-ga** [comment]
Thanks! I will test it.

If I want to mount it on a container, do I just add ` - &v3 ./outputs:/outputs` as follows?


```
version: '3.9'

x-base_service: &base_service
    ports:
      - "7860:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
      - &v3 ./outputs:/outputs
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
```
