### ISSUE TITLE
Generate does Nothing in Automatic1111

### ISSUE THREAD

**Issue by MrTyton** [AbdBarho/stable-diffusion-webui-docker#443]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

After inputting any prompts and clicking `Generate`, nothing happens.
![image](https://user-images.githubusercontent.com/1666715/236318839-401f1d85-90ed-4f11-b390-097ffc4fe4c9.png)

No progress bar, no system utilization increase, no image generated, anything. Clicking on `Interrupt` or `Skip` also doesn't do anything.

CLI output doesn't show anything
```
webui-docker-auto-1  | Calculating sha256 for /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt: cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516
webui-docker-auto-1  | Loading weights [cc6cb27103] from /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
webui-docker-auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inference.yaml
webui-docker-auto-1  | LatentDiffusion: Running in eps-prediction mode
webui-docker-auto-1  | DiffusionWrapper has 859.52 M params.
webui-docker-auto-1  | Applying xformers cross attention optimization.
webui-docker-auto-1  | Model loaded in 0.8s (create model: 0.2s, apply weights to model: 0.4s, apply half(): 0.2s).
```

Here are the docker-compose settings
```
  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:54
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api --no-gradio-queue
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
```

This used to work when I had the docker image from months ago, but I deleted the old one and upgraded to this and now it doesn't generate anything.

**Which UI**

auto

**Hardware / Software**

- OS: Unraid
- OS version: 6.11.5
- WSL version (if applicable): 
- Docker Version: 20.10.21
- Docker compose version: 2.17.3
- Repo version: from master
- RAM: 32GB
- GPU/VRAM: Nvidia RTX 3050 8GB VRAM

**Steps to Reproduce**

Install from scratch

**Additional context**
