### ISSUE TITLE
Please help!!!How to run docker container on 4 Gpus?Multi GPU?

### ISSUE THREAD

**Issue by randompaga** [AbdBarho/stable-diffusion-webui-docker#502]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

**Which UI**

auto or auto-cpu or invoke or sygil?

**Hardware / Software**

- OS: [e.g. Windows 10 / Ubuntu 22.04]
- OS version: 
- WSL version (if applicable): 
- Docker Version: 
- Docker compose version: 
- Repo version: 
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
1. you have to see how the ui itself uses multiple gpus, if that is even possible
2. for the container itself, you can create a `docker-compose.override.yml` and put something like this into it
```yml
x-base_service: &base_service
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                capabilities: [compute, utility]
                # put the indices of your GPUs here, like ['0', '1'] etc..
                device_ids: ['0']
```

**Comment by AbdBarho** [comment]
I think @randompaga wants to use multiple GPUs for the same container.

**Comment by caroaguilar** [comment]
It is possible and as @AbdBarho mentioned you need to create a docker-compose.override.yml with these contents

``` 
x-base_service: &base_service
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                capabilities: [compute, utility]
                # put the indices of your GPUs here, like ['0', '1'] etc..
                device_ids: ['0']
```

The most important part is this line `device_ids: ['0']` where you pass the GPU ids you want to use. You can refer to the nvidia docker container runtime docs, in the [GPU enumeration section](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/user-guide.html#gpu-enumeration) for that. 

But basically if you want to pass all the GPUs available you can set that line to: 
`device_ids: all`

or if you want specific GPUs you can pass a list of UUID or Ids, you can get your IDs by running `nvidia-smi` command. this will show you an output similar to:

```
nvidia-smi
Wed Jun 14 12:55:55 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   60C    P8    18W / 170W |    245MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:08:00.0 Off |                  N/A |
|  0%   57C    P8    15W / 170W |   9828MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4005      G   /usr/lib/xorg/Xorg                 80MiB |
|    0   N/A  N/A      4143      G   /usr/bin/gnome-shell               56MiB |
|    0   N/A  N/A    427987      C   python                            104MiB |
|    1   N/A  N/A      4005      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A    205894      C   python3                          9820MiB |
+-----------------------------------------------------------------------------+
```

The number before `NVIDIA GeForce` is what you need. For example for this GPU:

`|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |` 

if you want to use only that one the device_ids would look something like:  `device_ids: ['0']`

In your case you can also do something like `device_ids: ['0', '1', '2', '3']`, assuming those are the ids you get when running `nvidia-smi`
