### ISSUE TITLE
Exit code 137 for SDXL 1.0 and RAM at 16GB. MEM LEAK?

### ISSUE THREAD

**Issue by brentarias** [AbdBarho/stable-diffusion-webui-docker#575]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

Exit code 137 has been mentioned in both of the above places...but not in relation to checkpoint SDXL 1.0 failing...**with 16GB of RAM**.

**Describe the bug**

I have modified the docker compose file to increase the RAM to the maximum allowed (16GB):

```
x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7870}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        limits:
          memory: 16GB  # HIGHER VALUES ARE NOT HONORED.
        reservations:
          memory: 6GB
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
```
After launching with `docker compose --profile auto up --build` the container slowly consumes more memory until it reaches **11.45GB**,   then it is killed with exit code 137.  It seems as though it never reached the 16GB limit before failing...

![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/1289327/fadaa5da-cf9b-4a5e-aaf7-037b2cca421b)

I attempted to increase the memory to 20GB...but Docker did not honor that.  It instead gave me 16GB. Perhaps that is an inherent maximum.

When I select other checkpoints (downloaded from civitai), the memory consumed never seems to break 6GB.  However, the SDXL 1.0 consumes so much memory so fast...it _looks like a memory leak is occurring_.

**Which UI**

auto

**Hardware / Software**

- OS: Windows 11
- OS version: 22H2 (OS Build 22621.2134)
- WSL version (if applicable): WSL 2
- Docker Version: Docker Desktop 4.22.0
- Docker compose version: v2.20.2-desktop.1
- Repo version: "from master"
- RAM: 32GB
- GPU/VRAM: 8GB dedicated / 16 GB shared
- My Web UI is [v1.5](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)

Incidentally, my Docker Desktop for Windows configuration makes the following comment about WSL: "You don't have any WSL 2 distros installed."  Not sure if that is an issue.

![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/1289327/99a389a5-0408-451e-a828-a05be82aeacd)

**Steps to Reproduce**

 * I obtained the SDXL 1.0 on 8/23/2024 by cloning this address: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0

In the SDXL repo, there were three checkpoint files at the root:

 * sd_xl_base_1.0_0.9vae.safetensors  //This is the one I used, which failed.
 * sd_xl_base_1.0.safetensors
 * sd_xl_offset_example-lora_1.0.safetensors

I added the first of the above three to the pertinent docker volume model folder and attempted to load it in the UI.  After the `exit 137` occurred, I lifted my available memory to the maximum possible (16GB) and the problem still occurred again.
